### ISSUE TITLE
Figure out or disable previous and next buttons on bottom of doc pages 

### ISSUE THREAD

**Issue by BlackDragonBE** [viash-io/viash_web#10]
The buttons on the bottom of every page are seemingly random. If you take a look at the Introduction page for example, there shouldn't be a previous button and the next button should point to the Installation page. 
Instead, the previous button point to the FAQ and the next button points to the viash run command docs.  
  
We'll either have to figure out how to create sensible links with these, or disable them altogether if it's too much of a hassle.

**Comment by rcannood** [comment]
Merge with the main branch, I fixed this yesterday ;)

**Comment by BlackDragonBE** [comment]
I updated my branch from main and can confirm the buttons are now linking correctly! Thanks!
