### ISSUE TITLE
Add syntax highlighting for additional languages

### ISSUE THREAD

**Issue by BlackDragonBE** [viash-io/viash_web#20]
Currently, the following languages aren't syntax highlighted in code blocks with hljs while it [definitely supports that](https://highlightjs.org/static/demo/):

- Python
- R
- Markdown
- Probably more

**Comment by BlackDragonBE** [comment]
I've added the extra highlighting, it was just a case of adding some extra variables and loading the right hljs libraries. Now our docs are easier to read again. The changes are included in #22.

**Comment by rcannood** [comment]
:+1:

**Comment by rcannood** [comment]
#22 was merged!
