### ISSUE TITLE
Create contributing guidelines

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash_web#3]
Write `content_raw/docs/contributing/guidelines.Rmd`.

I quite like the Spark contributing guidelines. Extensive guidelines are available on the [website](https://spark.apache.org/contributing.html). Development-focused contributing guidelines are available on their [GitHub repository](https://github.com/apache/spark/blob/master/CONTRIBUTING.md). We can also borrow some lines from [dynverse/dynverse](https://github.com/dynverse/dynverse/blob/master/CONTRIBUTING.md).

**Comment by rcannood** [comment]
and [https://getdoks.org/docs/contributing/how-to-contribute/](https://getdoks.org/docs/contributing/how-to-contribute/) as well

**Comment by BlackDragonBE** [comment]
@rcannood 

Initial version of this page is included in PR #39 
I've cherry picked from the suggested sources and made the page our own.

**Comment by rcannood** [comment]
Thanks @BlackDragonBE!
