### ISSUE TITLE
Rework installation documentation

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash_web#4]
The installation documentation `content_raw/docs/prologue/installation.Rmd` needs to be a lot more streamlined. The [nextflow website](https://www.nextflow.io/index.html#GetStarted) is a good example of how simple installing it can be. We're working on the `viash_bootstrap` component, available here: [https://viash.io/viash_bootstrap](https://viash.io/viash_bootstrap).

**Comment by BlackDragonBE** [comment]
Nextflow also has detailed installation instructions in their docs: https://www.nextflow.io/docs/latest/getstarted.html#installation
Maybe we can have simplified steps like theirs on our homepage? That would be pretty user friendly.

**Comment by BlackDragonBE** [comment]
Here's a (very rough) mockup of what that might look like: 

![mockup](https://user-images.githubusercontent.com/8495163/120098974-374caa80-c139-11eb-875d-fc7993d4e46d.png)

**Comment by tverbeiren** [comment]
Is used the following last week until the work on the website started:

```sh
curl -fsSL https://viash.io/viash_bootstrap | bash
```

I set it up again, albeit in a different way to again be possible:

```sh
wget -qO- http://get.viash.io | bash
```

Or, if you want with `curl`:

```sh
curl -fsSL http://get.viash.io | bash
```

Additional options can be set immediately or during a second run of the (then locally installed version of the boostrap tool), using the following syntax:

```sh
curl -fsSL http://get.viash.io | bash -s -- -h
```

**Comment by BlackDragonBE** [comment]
I've simplified the instructions, we now instruct users to install viash via the bootstrap: https://github.com/viash-io/viash_web/commit/55c7876ce2732ecd89a12cc236b5658a6028a98d

This is included in #22 

I've changed my mind about adding the installation instructions to the homepage, I think the **Get started** button is sufficient, adding too much bells and whistles to the homepage takes away from the clean look and I think it's important to know what viash is before installing it anyway. 
I'll close this issue once the PR has been merged.

**Comment by rcannood** [comment]
#22 was merged!

**Comment by rcannood** [comment]
Actually, I changed my mind! :P 

This was not documented:

> Additional options can be set immediately or during a second run of the (then locally installed version of the boostrap tool), using the following syntax:
> ```
> curl -fsSL get.viash.io | bash -s -- -h
> ```

This is important to note, because you might want to be able to pull a specific version of viash or use any of the other parameters. Example:

```bash
curl -fsSL get.viash.io | bash -s -- --bin exe --registry openproblems --tag 0.5.0-rc2
```

**Comment by BlackDragonBE** [comment]
@rcannood Good point! I'll document the bootstrap options as well.

**Comment by tverbeiren** [comment]
Sure, and perhaps standardize on `wget`? The arguments are easier to remember imho.

**Comment by BlackDragonBE** [comment]
I've added additional instructions for the bootstrap and automatically list the options: https://github.com/viash-io/viash_web/commit/f9c9088cd7085269dc9907aee77fb303a76417a9
