### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash_web#5]
I ported the documentation from [https://www.data-intuitive.com/viash_docs](https://www.data-intuitive.com/viash_docs) to [https://viash.io](https://viash.io).

I primarily focussed on porting the content, but didn't fix all of the links. 

@BlackDragonBE Could you go through every Rmd file and fix the broken links? :bow:

**Comment by BlackDragonBE** [comment]
All broken links are fixed now in my branch. Next up is checking if all of them are correct in both the text and scripts, then I'll make a pull request.

**Comment by BlackDragonBE** [comment]
This issue is fixed once #11 is merged.

**Comment by BlackDragonBE** [comment]
Fixed in #11
