### ISSUE TITLE
Add reference for nextflow config

### ISSUE THREAD

**Issue by rcannood** [viash-io/viash_web#6]
The current information on Nextflow was more of a guide to how to write a nextflow pipeline with viash modules, so I put it in a separate category.

However, the reference document on nextflow is now missing.

**Comment by rcannood** [comment]
Created a branch for this, [feature_reworknextflow](https://github.com/viash-io/viash_web/tree/feature_reworknextflow).

Bringing @tverbeiren into the discussion! ^^

**Comment by tverbeiren** [comment]
@rcannood Please review

**Comment by rcannood** [comment]
Merged by #30!
