### ISSUE TITLE
All references to 'data-intuitive.com' and 'viash_docs' should be replaced in all text, links and scripts

### ISSUE THREAD

**Issue by BlackDragonBE** [viash-io/viash_web#7]
The bash creating component page for example still used data-intuitive links as examples instead of viash-io.
I'll be going through all pages and scripts to fix this issue.

**Comment by rcannood** [comment]
Don't blindly replace `data-intuitive` with `viash-io` everywhere ([example](https://github.com/viash-io/viash_web/commit/bd46fc0909e440b35d21c2d03c05ec377f65859d#diff-c1a954c7eb38848d17252afe4bf17d68a2434e0d9033229e6e93326d03c3567cL30-R30)); the new domain is `https://viash.io` and not `https://www.viash-io.com`.

**Comment by BlackDragonBE** [comment]
@rcannood All references to the old Github should be replaced though:
Old address: http://www.data-intuitive.com/viash_docs/
New address: https://github.com/viash-io/viash_web/

I am doing a few rounds of replacing, the first is making sure there are no 404's, as stated in #5.
Those commits are a WIP, the pull request will be final.

**Comment by rcannood** [comment]
I think `http://www.data-intuitive.com/viash_docs/` needs to be replaced with `https://viash.io`. 
And `https://github.com/data-intuitive/viash` with `https://github.com/viash-io/viash`.

**Comment by BlackDragonBE** [comment]
Agreed! That's a

**Comment by BlackDragonBE** [comment]
Agreed, that's a clear list! Thanks for that.

**Comment by BlackDragonBE** [comment]
Fixed all references to "old" URLs in text and scripts in my branch.

**Comment by BlackDragonBE** [comment]
This issue is fixed once #11 is merged.

**Comment by BlackDragonBE** [comment]
Fixed in #11.
