### ISSUE TITLE
How to debug based on the given viash environment

### ISSUE THREAD

**Issue by ChineseBest** [viash-io/viash_web#87]
I met errors when I intend to train my model based on pytorch, which is same as the error before I change the memory of the docker. I wonder if there are any approaches that I can utilize to detect the bugs and find the detailed information of it (like error report). Thanks.

**Comment by rcannood** [comment]
Please take a look at the most [frequently asked questions](https://openproblems.bio/neurips_docs/submission/faq/). If this does not solve your problem, please post questions about the NeurIPS competition in the [Discord channel](https://openproblems.bio/neurips_docs/about/discord/).
